
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '253BC877E85C01A0BD013F0527025863'
    
_lr_action_items = {'(':([5,],[10,]),':':([23,],[29,]),'PARTITION_B':([0,3,18,20,],[2,2,-2,-3,]),',':([5,6,7,8,19,26,31,32,35,],[-6,12,-5,12,-4,-7,34,-9,-8,]),';':([5,6,7,8,19,26,31,32,35,],[-6,11,-5,13,-4,-7,33,-9,-8,]),'$end':([4,24,27,30,],[0,-1,-11,-10,]),'END':([11,13,21,22,25,28,33,],[18,20,27,-13,30,-12,-14,]),'PARTITION_A':([0,3,18,20,],[1,1,-2,-3,]),')':([17,],[26,]),'PREFERENCE_LISTS_B':([9,15,18,20,27,30,],[14,14,-2,-3,-11,-10,]),'INT':([10,],[17,]),'ID':([1,2,12,14,16,21,22,25,28,29,33,34,],[5,5,5,23,23,23,-13,23,-12,32,-14,35,]),'PREFERENCE_LISTS_A':([9,15,18,20,27,30,],[16,16,-2,-3,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'vertex_list':([29,],[31,]),'preference_lists':([14,16,],[21,25,]),'nodes':([0,3,],[3,9,]),'pvertex_list':([1,2,],[6,8,]),'pvertex':([1,2,12,],[7,7,19,]),'pref_list':([14,16,21,25,],[22,22,28,28,]),'edges':([9,15,],[15,24,]),'graph':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> graph","S'",1,None,None,None),
  ('graph -> nodes nodes edges edges','graph',4,'p_graph','graph_parser.py',10),
  ('nodes -> PARTITION_A pvertex_list ; END','nodes',4,'p_partition_A','graph_parser.py',15),
  ('nodes -> PARTITION_B pvertex_list ; END','nodes',4,'p_partition_B','graph_parser.py',20),
  ('pvertex_list -> pvertex_list , pvertex','pvertex_list',3,'p_pvertex_list','graph_parser.py',26),
  ('pvertex_list -> pvertex','pvertex_list',1,'p_pvertex_list_terminating','graph_parser.py',31),
  ('pvertex -> ID','pvertex',1,'p_pvertex','graph_parser.py',37),
  ('pvertex -> ID ( INT )','pvertex',4,'p_pvertex_capacity','graph_parser.py',42),
  ('vertex_list -> vertex_list , ID','vertex_list',3,'p_vertex_list','graph_parser.py',47),
  ('vertex_list -> ID','vertex_list',1,'p_vertex_list_terminating','graph_parser.py',52),
  ('edges -> PREFERENCE_LISTS_A preference_lists END','edges',3,'p_preference_lists_A','graph_parser.py',57),
  ('edges -> PREFERENCE_LISTS_B preference_lists END','edges',3,'p_preference_lists_B','graph_parser.py',62),
  ('preference_lists -> preference_lists pref_list','preference_lists',2,'p_preference_lists','graph_parser.py',67),
  ('preference_lists -> pref_list','preference_lists',1,'p_preference_lists_terminating','graph_parser.py',72),
  ('pref_list -> ID : vertex_list ;','pref_list',4,'p_pref_list','graph_parser.py',77),
]
