
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A956629878C4DDDF7994DEFA5698596B'
    
_lr_action_items = {'PREFERENCE_LISTS_B':([5,12,24,25,27,29,],[10,10,-2,-3,-12,-11,]),';':([6,7,8,9,23,31,32,33,37,38,],[-6,-5,15,16,-4,-7,36,-10,-8,-9,]),'$end':([1,21,27,29,],[0,-1,-12,-11,]),',':([6,7,8,9,22,23,31,32,33,37,38,],[-6,-5,14,14,30,-4,-7,35,-10,-8,-9,]),'PREFERENCE_LISTS_A':([5,12,24,25,27,29,],[11,11,-2,-3,-12,-11,]),':':([17,],[26,]),'PARTITION_B':([0,2,24,25,],[4,4,-2,-3,]),'INT':([13,30,],[22,34,]),'END':([15,16,18,19,20,28,36,],[24,25,-14,27,29,-13,-15,]),'ID':([3,4,10,11,14,18,19,20,26,28,35,36,],[6,6,17,17,6,-14,17,17,33,-13,38,-15,]),'(':([6,],[13,]),'PARTITION_A':([0,2,24,25,],[3,3,-2,-3,]),')':([22,34,],[31,37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'edges':([5,12,],[12,21,]),'pref_list':([10,11,19,20,],[18,18,28,28,]),'graph':([0,],[1,]),'nodes':([0,2,],[2,5,]),'preference_lists':([10,11,],[19,20,]),'vertex_list':([26,],[32,]),'pvertex':([3,4,14,],[7,7,23,]),'pvertex_list':([3,4,],[8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> graph","S'",1,None,None,None),
  ('graph -> nodes nodes edges edges','graph',4,'p_graph','graph_parser.py',10),
  ('nodes -> PARTITION_A pvertex_list ; END','nodes',4,'p_partition_A','graph_parser.py',15),
  ('nodes -> PARTITION_B pvertex_list ; END','nodes',4,'p_partition_B','graph_parser.py',20),
  ('pvertex_list -> pvertex_list , pvertex','pvertex_list',3,'p_pvertex_list','graph_parser.py',26),
  ('pvertex_list -> pvertex','pvertex_list',1,'p_pvertex_list_terminating','graph_parser.py',31),
  ('pvertex -> ID','pvertex',1,'p_pvertex_one','graph_parser.py',37),
  ('pvertex -> ID ( INT )','pvertex',4,'p_pvertex_capacity_upper','graph_parser.py',42),
  ('pvertex -> ID ( INT , INT )','pvertex',6,'p_pvertex_capacity_upper_and_lower','graph_parser.py',47),
  ('vertex_list -> vertex_list , ID','vertex_list',3,'p_vertex_list','graph_parser.py',52),
  ('vertex_list -> ID','vertex_list',1,'p_vertex_list_terminating','graph_parser.py',57),
  ('edges -> PREFERENCE_LISTS_A preference_lists END','edges',3,'p_preference_lists_A','graph_parser.py',62),
  ('edges -> PREFERENCE_LISTS_B preference_lists END','edges',3,'p_preference_lists_B','graph_parser.py',67),
  ('preference_lists -> preference_lists pref_list','preference_lists',2,'p_preference_lists','graph_parser.py',72),
  ('preference_lists -> pref_list','preference_lists',1,'p_preference_lists_terminating','graph_parser.py',77),
  ('pref_list -> ID : vertex_list ;','pref_list',4,'p_pref_list','graph_parser.py',82),
]
